manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: timowielink
      url-base: https://github.com/TimoWielink

  projects:
    - name: zmk
      remote: timowielink
      revision: main
      import: app/west.yml
  self:
    path: config
