name: Build ZMK firmware

on:
  push:
    branches:
      - '*'
    paths:
      - 'config/**'
      - '.github/workflows/**'
      - 'boards/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'config/**'
      - '.github/workflows/**'
      - 'boards/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: config
      config_repo: TimoWielink/zmk-config-minimalpad
      extra_modules: elpekenin/zmk-userspace
      archive_name: firmware
